directories:
  output: build-final
  buildResources: build
appId: com.toolcrypt.csvmanager
productName: ToolCrypt
files:
  - filter:
      - dist/**/*
      - src/renderer/**/*
      - node_modules/**/*
      - package.json
      - assets/**/*
win:
  target: nsis
  publisherName: ToolCrypt
  icon: assets/icon.ico
  requestedExecutionLevel: asInvoker
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  displayLanguageSelector: false
  language: '1033'
  installerIcon: assets/icon.ico
  uninstallerIcon: assets/icon.ico
publish:
  provider: github
  owner: tanhdabez
  repo: ToolCrypt
electronVersion: 27.3.11
